services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8000:8000
    environment:
      LOG_LEVEL: debug
      PG_DSN: postgres://postgres:secret@postgres/postgres?sslmode=disable
      HTTP_LISTEN: :8000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 5s
      retries: 5
    
  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/database
    command:
      ["-path", "/database", "-database", "postgres://postgres:secret@postgres:5432/postgres?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy
